2023-09-12 02:56:16,253 DEBUG    root            Loaded Command Group: ['gcloud', 'app']
2023-09-12 02:56:16,541 DEBUG    root            Loaded Command Group: ['gcloud', 'app', 'deploy']
2023-09-12 02:56:16,546 DEBUG    root            Running [gcloud.app.deploy] with arguments: []
2023-09-12 02:56:16,575 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,578 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,580 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,581 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,584 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,595 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,597 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,598 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,599 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,602 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,626 DEBUG    root            Loading runtimes experiment config from [gs://runtime-builders/experiments.yaml]
2023-09-12 02:56:16,639 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,641 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,643 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,644 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,646 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,659 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,661 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,663 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,664 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,667 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,699 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,701 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,703 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,703 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,706 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,719 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,721 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,722 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,723 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,726 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,726 INFO     root            Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7f65111a4100>]
2023-09-12 02:56:16,800 DEBUG    root            Flex image build option: FlexImageBuildOptions.ON_SERVER
2023-09-12 02:56:16,842 DEBUG    root            API endpoint: [https://appengine.googleapis.com/], API version: [v1]
2023-09-12 02:56:16,862 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,864 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,866 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,866 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:16,869 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:16,926 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:16,928 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:16,930 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:16,930 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform
2023-09-12 02:56:16,934 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform HTTP/1.1" 200 870
2023-09-12 02:56:27,890 INFO     ___FILE_ONLY___ Enabling service [appengine.googleapis.com] on project [466659303869]...

2023-09-12 02:56:27,920 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:27,922 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:27,924 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:27,925 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:27,928 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:28,252 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:28,254 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:28,256 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:28,257 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:28,260 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:31,240 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true
2023-09-12 02:56:31,242 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2023-09-12 02:56:31,244 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 141
2023-09-12 02:56:31,245 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token
2023-09-12 02:56:31,247 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/466659303869-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 870
2023-09-12 02:56:31,346 INFO     ___FILE_ONLY___ Operation "operations/acat.p2-466659303869-6d0df819-a3bc-4ffa-9d80-1cb07b75b1bd" finished successfully.

2023-09-12 02:56:31,346 DEBUG    root            Request returned no response, retrying
2023-09-12 02:56:31,348 DEBUG    root            Retrying request to url https://appengine.googleapis.com/v1/apps/around-project-397816?alt=json after exception Retry
2023-09-12 02:56:33,408 DEBUG    root            Request returned no response, retrying
2023-09-12 02:56:33,410 DEBUG    root            Retrying request to url https://appengine.googleapis.com/v1/apps/around-project-397816?alt=json after exception Retry
2023-09-12 02:56:37,938 DEBUG    root            No app found:
Traceback (most recent call last):
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 838, in _PossiblyCreateApp
    return api_client.GetApplication()
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 76, in GetApplication
    return self.client.apps.Get(request)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/generated_clients/apis/appengine/v1/appengine_v1_client.py", line 1118, in Get
    return self._RunMethod(
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://appengine.googleapis.com/v1/apps/around-project-397816?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Tue, 12 Sep 2023 02:56:37 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': '404', 'content-length': '403', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 404,
    "message": "Resource 'projects/around-project-397816/locations/global/applications/around-project-397816' was not found",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ResourceInfo",
        "resourceName": "projects/around-project-397816/locations/global/applications/around-project-397816"
      }
    ]
  }
}
>
2023-09-12 02:56:37,946 INFO     ___FILE_ONLY___ You are creating an app for project [around-project-397816].

2023-09-12 02:56:37,946 WARNING  root            Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.

2023-09-12 02:57:11,166 DEBUG    root            (gcloud.app.deploy) PERMISSION_DENIED: The caller does not have permission
Traceback (most recent call last):
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 838, in _PossiblyCreateApp
    return api_client.GetApplication()
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 76, in GetApplication
    return self.client.apps.Get(request)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/generated_clients/apis/appengine/v1/appengine_v1_client.py", line 1118, in Get
    return self._RunMethod(
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://appengine.googleapis.com/v1/apps/around-project-397816?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Tue, 12 Sep 2023 02:56:37 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': '404', 'content-length': '403', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 404,
    "message": "Resource 'projects/around-project-397816/locations/global/applications/around-project-397816' was not found",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ResourceInfo",
        "resourceName": "projects/around-project-397816/locations/global/applications/around-project-397816"
      }
    ]
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/snap/google-cloud-cli/167/lib/surface/app/deploy.py", line 127, in Run
    return deploy_util.RunDeploy(
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 653, in RunDeploy
    app = _PossiblyCreateApp(api_client, project)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 851, in _PossiblyCreateApp
    create_util.CreateAppInteractively(api_client, project)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/create_util.py", line 146, in CreateAppInteractively
    CreateApp(
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/command_lib/app/create_util.py", line 94, in CreateApp
    api_client.CreateApp(region, service_account=service_account)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 142, in CreateApp
    operation = self.client.apps.Create(create_request)
  File "/snap/google-cloud-cli/167/lib/googlecloudsdk/generated_clients/apis/appengine/v1/appengine_v1_client.py", line 1092, in Create
    return self._RunMethod(
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/snap/google-cloud-cli/167/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://appengine.googleapis.com/v1/apps?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Tue, 12 Sep 2023 02:57:11 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': '403', 'content-length': '126', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>
2023-09-12 02:57:11,171 ERROR    root            (gcloud.app.deploy) PERMISSION_DENIED: The caller does not have permission
